name: SSHPASS Github Action
inputs:
  host:
    description: "SSHPASS host"
    required: true
  port:
    description: "SSHPASS port"
    required: false
    default: 22
  username:
    description: "SSHPASS username"
    required: true
  password:
    description: "SSHPASS password"
    required: true
  run:
    description: "SSHPASS commands to run"
    required: true

description: 'SSHPASS Github Action'
branding:
  icon: dollar-sign
  color: gray-dark
runs-on: ubuntu-18.04
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    HOST: ${{ inputs.host }}
    PORT: ${{ inputs.port }}
    USERNAME: ${{ inputs.username }}
    PASSWORD: ${{ inputs.password }}
    RUN: ${{ inputs.run }}
